### ISSUE TITLE
bug in joinMonster.getNode(): def.args not iterable 

### ISSUE THREAD

**Issue by moltco** [acarl005/join-monster#476]
When using joinMonster.getNode to resolve the 'node' query (as per Relay spec) the resolver throws an error def.args not iterable.

The reproducible code (Node, express) is available here [https://github.com/moltco/monstertest](https://github.com/moltco/monstertest )

I use a simple schema for User Type that implements nodeInterface with globalId and 'user' query to resolve User Type and 'node' query to resolve any node. 

I use this for resolving the node query (as per join monster docs):
```
const { nodeInterface, nodeField } = nodeDefinitions(
    // https://join-monster.readthedocs.io/en/v0.9.9/relay/
    // resolve the ID to an object
    (globalId, context, resolveInfo) => {
      // parse the globalID
      const { type, id } = fromGlobalId(globalId)

      // pass the type name and other info. `joinMonster` will find the type from the name and write the SQL
      return joinMonster.getNode(type, resolveInfo, context, id,//String(id), 
        async sql => dbExec(sql)
      )
    },
    // determines the type. Join Monster places that type onto the result object on the "__type__" property
    obj => obj.__type__
  )
```

I use query on /graphql such as 
```
query { 
      node(id:"VXNlcjplZmNkMmE3MC02M2EyLTRhZDMtYTY2OS1kY2FiYzYyMzhmMmM=")  
     {id} 
}
```
Which fails with ```def.args is not iterable``` error before SQL is formed by join monster. The error is raised at 

joinMonster: query-ast-to-sql-ast/index.js:116:0 -> "sqlASTNode.args = (0, _values.getArgumentValues)(field, queryASTNode, this.variableValues);"

and by _values.getArgumentValues from grapql:/execution/value.js:183:24 

the field.args is passed as an empty object {} and as such is not iterable. When it gets to 183:24 the line says 
```
// note: def.args = {}
for (const argDef of def.args) {
...
}
```
Am I doing something wrong or is this a bug in joinMonster where it's not passing field.args as iterable?? Based on my very simple sample code above it feels like joinMonster needs a patch.

Can you please help?

**Comment by moltco** [comment]
If I add to join-monster/dist/query-ast-t-sql-ast/index.js:116 the following line to ensure field.args are an interable array 
```
 if (field && field.args && !Array.isArray(field.args)) field.args = [field.args]; 
 // sqlASTNode.args = (0, _values.getArgumentValues)(field, queryASTNode, this.variableValues);
```

Perhaps there is no need for null checks and a more elegant way of doing this. Also noted the type passed GraphQL-js 16+ when resolving node query (at least) needs to be a string name not object so something like obj.__type__?.name insted of obj.__type__ as in joinMonster docs.

**Comment by nicoabie** [comment]
Hi @moltco I tried downloading the example you provided but couldn't make it work.

Can you provide one using https://github.com/join-monster/join-monster-sscce ? I'd love to merge your PR but I need to see it failing first.

Thanks and have a nice weekend

**Comment by molt2020** [comment]
Hi @nicoabie, I'd really like to help but this bug has been reported 2+ years ago so my memory is a bit flaky and I don't use the join-monster of graphql at this time so it's not really fresh in mind for me to create a new SSCCE repository.

I do believe that the repo I uploaded can demonstrate the bug pretty clearly (https://github.com/moltco/monstertest) - I just tried again to make sure it breaks and it does. Where do you get stuck?

I do 
`yarn run devstart`
then run query on localhost:3000/graphql with the following text

```
query
{
  node(id:"VXNlcjplZmNkMmE3MC02M2EyLTRhZDMtYTY2OS1kY2FiYzYyMzhmMmM=")
  {id
  }
}
```

and I get otput:
```

{
  "errors": [
    {
      "message": "def.args is not iterable",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "node"
      ]
    }
  ],
  "data": {
    "node": null
  }
}

```

I can record the screen if it helps or if this the above works for you I could try cloning again my repo to double-check? Perhaps you are using newer version of libraries that may have solved this issue? Try installing the exact versions in my package.json?

Sorry but replicating as per sccee seems a lot of work as I don't recall the intricacies of the bug or technology anymore.

**Comment by nicoabie** [comment]
@moltco @molt2020  I create this PR with your code https://github.com/join-monster/join-monster-sscce/pull/1 showing it works.

Updating your local repo  join-monster with `yarn upgrade join-monster` and change line 53 to `obj => obj.__type__ ` will make it work for you. If not feel free to reopen.
