### ISSUE TITLE
Remove requirement for uniqueKey to be defined

### ISSUE THREAD

**Issue by Megapixel99** [acarl005/join-monster#483]
### Describe the problem you'd like to have solved

In some cases it is not ideal to have a `uniqueKey` parameter(s) for your SQL. If your SQL has a unique key or keys that is fine but not all SQL rows/columns are unique in the database I am using, so some rows are hidden in the response from join monster since they are not unique (as a basic example: in a table of first_name, last_name, and nick_name, multiple people can have the same first name, last name and nickname or some combination thereof. `uniqueKey` would hide any number of these rows). I was able to get around this initially by mapping every key/column to the `uniqueKey` array which made the query very bloated and slow (shown below). As of this comment I have figured out a new workaround (shown below) but I do not believe it is optimal; however it is faster than my initial work around.

### Describe the ideal solution

Make `uniqueKey` optional for SQL queries.

## Alternatives and current work-arounds

My initial workaround (mapping every key/column to the `uniqueKey` array)

```
unrelated code
...
// data set elsewhere
let owner = "owner"
let arrColumns = [{
   table: "x",
   column: "y",
}, {
   table: "x",
   column: "z",
}]
....
unrelated code
....
extensions: {
   joinMonster: {
     sqlTable: `${owner}.${arrColumns[0].table}`,
     uniqueKey: arrColumns.map((e) => e.column),
   }
 }
...
unrelated code
```
My current workaround:
```
unrelated code
...
extensions: {
   joinMonster: {
     sqlTable: `${owner}.${arrColumns[0].table}`,
     uniqueKey: [],
   }
 }
...
unrelated code
...
resolve: (parent, args, context, resolveInfo) => {
  return new Promise((resolve, reject) => {
     joinMonster(resolveInfo, {}, sql => {
     //  replace(/\n   AS ,/g, "") removes the empty array from uniqueKey
     resolve(sql.replace(/\n   AS ,/g, ""));
     // error supression
     return Promise.resolve([]);
     });
   }).then(knex.raw).catch(handleErr);
}
...
unrelated code
```

Please let me know if anything needs to be clarified.

**Comment by nicoabie** [comment]
Join monster uses https://github.com/CoursePark/NestHydrationJS behind the scenes to compose object relations from table mappings. in order to achieve that transformation is it necessary to uniquely identify the objects.

There is no way to make uniqueKey optional and having that feature.
