### ISSUE TITLE
Some disjoint fields of the same union type are discarded 

### ISSUE THREAD

**Issue by Grundlefleck** [acarl005/join-monster#512]
Thank you for taking the time to read this, and to have produced and shared this library. 

### Description

Requesting disjoint fields of the same union type at different locations results in choosing one of the results. The data returned will "pick" one shape, and return null where the fields are not included in that. It is non-deterministic, and whichever result is encountered first will "win".

### Reproduction

I'll have a PR incoming with a test case but in the meantime, using the schema from the project's test suite, a query like this:

```
    {
      user(id: 1) {
        writtenMaterial1 {
          ... on Comment {
            id
            author {
              capitalizedLastName # <-- First "disjoint" field selection from author type
            }
          }
          ... on Post {
            id
            author {
              email # <-- Second "disjoint" field selection from author type
            }
          }
        }
      }
    }
```
Where the `author` is a `User`, via the `AuthoredUnion` type of `[Comment, Post]`, and `capitalizedLastName` and `email` are both string fields on `User`.

On running this query, either the Comment's author will have a non-null `capitalizedLastName` and the Post's author will have a null `email` or vice-versa. In both cases the underlying data has non-null values for both `capitalizedLastName` and `email`. However, one or the other is discarded. 

From local debugging and experimentation, I believe the cause is in [resolve-unions.js](https://github.com/join-monster/join-monster/blob/master/src/resolve-unions.js#L23). The first "qualified field" (i.e. suffixed with the union type member) is used as the field, where both are available. In the above example, during `resolveUnions()`, the data will include:
```{
  [snip -- other resolved values]
  author@Comment: { id: [the-id], capitalizedName: "The non-null capitalizedName value" },
  author@Post: { id: [the-id], email: "The non-null email value" },
}
```
The first encountered is selected as long as the original field is non-null. Then the subsequent "correct" values are ignored.

If I understand the internals correctly, it's possible to know exactly which of the resolved values to take, as we know for that row there is a `$type` value for what it has been resolved as (where `$type` what will be returned by `resolveType()` on the schema definition). 

One workaround is to ensure that there are no disjoint fields queried across union types, and each union member's type will be satisfied. But that's not easy to enforce (or even describe) to clients 😄 

[PR](https://github.com/join-monster/join-monster/pull/513) with a test case to demonstrate the issue, and a fix. However, it is not compatible with batching, so it's incomplete at best.

### Environment

> Please provide the following:

- **Version of this library used:** demonstrable on master (3.3.2) but experienced on (3.1.1)
- **Version of the platform or framework used, if applicable:** Don't know
- **Other relevant versions (language, server software, OS, browser):** across all DB implementations in the test suite.
- **Other modules/plugins/libraries that might be involved:**None, appears entirely rooted in JoinMonster source code.

**Comment by nicoabie** [comment]
@Grundlefleck I'd love your input in the solution I've proposed https://github.com/join-monster/join-monster/pull/519

And If you can tell me if you have a test for sqlBatch or how did you know it would not work there.

Thanks for such a detailed issue, investigation, pull request and patience.

**Comment by nicoabie** [comment]
I added this test https://github.com/join-monster/join-monster/pull/519/commits/06f2a263a86f2bc30448ef860578a82b12c700a4 and it passes in both batch and join modes. 

I also tested that on master. with same results.

Note that there is an extra object, I believe disjoint fields need more work. 

We could merge my PR that make multiple disjoint fields work in join mode which solves @Grundlefleck 

Then work in PRs addressing:

- multiple disjoint in batch mode
- remove extra object in single disjoint in batch mode
- remove extra object in single disjoint in join mode

**Comment by nicoabie** [comment]
fixed by #519

**Comment by Grundlefleck** [comment]
Hi @nicoabie thanks for looking into it.

> @Grundlefleck I'd love your input in the solution I've proposed #519

I confess I don't really understand how it works, but probably it's because I can't visualise the runtime types when `moveProp` is called. Is the strategy to merge (via `Object.assign`) the field representing the unioned type? So in the example test case, the `author` field would be like: `{ capitalizedLastName: "...", email: "..." }` and that would be passed back?

> And If you can tell me if you have a test for sqlBatch or how did you know it would not work there.

Only from running e.g. `npm run test` which would execute the same tests using `STRATEGY=batch`. I didn't even consider batch mode until I ran the test suite... which is a sign of a great test suite! 😄 

> Thanks for such a detailed issue, investigation, pull request and patience.

No, thank you.

**Comment by nicoabie** [comment]
The the problem was that the two disjoint fields where coming from the db in different objects. 
So the latter overrode the first one, that is why you were alway having just one of those. 

Now I check if we have a result that is an object and a new piece comes, we just merge it.

`{ author: { capitalizedLastName: "..." } }  +   { author: { email: "..." } } = { author: { capitalizedLastName: "...",  email: "..." } } `

in the end I was able to fix both modes with same approach in different places:

https://github.com/join-monster/join-monster/blob/a5395c589d727f69f29ca36c19aea227f659f1b0/src/batch-planner/index.js#L102 fix for batch mode

https://github.com/join-monster/join-monster/blob/a5395c589d727f69f29ca36c19aea227f659f1b0/src/resolve-unions.js#L13 fix for join mode

**Comment by Grundlefleck** [comment]
> we just merge it.

Gotcha. I had in my head that the resultant object needed to match the fields being requested, and that any extra fields not requested in the GQL query input might trip some validation.

Not sure where I got that from, but if it's not a concern then making all fields available is way simpler than trying to wrangle a call to `resolveType()`.

**Comment by nicoabie** [comment]
Yes, It will match exactly the fields requested. The thing is that the fields came is different objects. That's all :)
